# Generated by Django 2.1.8 on 2019-06-01 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('activity', models.CharField(choices=[('1', '비활동적'), ('2', '저활동적'), ('3', '활동적'), ('4', '매우 활동적')], max_length=1)),
                ('calorie', models.IntegerField()),
                ('carbohydrate_low', models.IntegerField()),
                ('carbohydrate_high', models.IntegerField()),
                ('protein_low', models.IntegerField()),
                ('protein_high', models.IntegerField()),
                ('fat_low', models.IntegerField()),
                ('fat_high', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
