# Generated by Django 2.1.8 on 2019-06-01 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='user_id',
        ),
        migrations.AddField(
            model_name='board',
            name='calorie',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='carbohydrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='protein',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
    ]
