# Generated by Django 2.1.8 on 2019-06-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190601_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user',
            new_name='user_id',
        ),
    ]
